@startuml
' This UML source uses PlantUML format.
' https://plantuml.com/sequence-diagram for syntax details.
' Optional styles

skinparam shadowing false
skinparam SequenceMessageAlign direction

autonumber

actor User as user
participant "Partner" as part
participant "Mercuryo" as merc

user -> part: Хочу IBAN
part -> merc: /sdk-partner/sign-in()
part -> merc: /b2b/user/data()
alt#gold #lightblue KYC1
merc --> part: KYC1
part -> merc: get/kyc-access-token
merc --> part: redirect_url
part -> user: redirect
user -> front: KYC2
front -> user: redirect to Partner
part -> merc: /b2b/user/data()
end
merc --> part: KYC2
part -> merc: /createIban()
merc --> part: IBAN number
part --> user: IBAN number

@enduml
