@startuml
' This UML source uses PlantUML format.
' https://plantuml.com/sequence-diagram for syntax details.
' Optional styles

skinparam shadowing false
skinparam SequenceMessageAlign direction

autonumber

actor User as user
participant "Partner" as part
participant "Mercuryo" as merc

part -> merc: /b2b/user/data()
part -> merc: /b2b/user/iban
user -> part: Вывести средства со своего IBAN
part -> merc: /b2b/fiat/withdraw
merc --> part: Done 
part --> user: Done
@enduml
