@startuml
' This UML source uses PlantUML format.
' https://plantuml.com/sequence-diagram for syntax details.
' Optional styles

skinparam shadowing false
skinparam SequenceMessageAlign direction

autonumber

actor User as user
participant "Partner" as part
participant "Mercuryo" as merc

user -> part: Купить крипту
part -> merc: /lib/currencies()
part -> merc: /lib/countries()
part -> merc: /sdk-partner/sign-in()
part -> merc: /b2b/buy/methods()
merc --> part: Payment methods
user -> part: Купить крипту переводом на счет
user -> part: Currency, Amount
part -> merc: /b2b/buy/rate(From, To, Amount, PM-ID)
note right
Замораживает новое значение
курса при каждом запросе **""/b2b/buy/rate""**
end note
merc --> part: Buy-token
user -> part: Wallet для вывода криптовалюты
part -> merc: /b2b/buy(mrch-trx-id opt, buy-token, wallet)
merc --> part: Payment instructions for user, merchant-trx-id
part -> user: Payment Instructions
user -> merc: Payment
merc -> merc: Deposit processing
merc -> merc: Fiat withdrawal
part -> merc: /b2b/buy/:merch_trx_id:/status()
merc --> part: TRX status
part --> user: Transaction Result

@enduml
